import type { Placement, Step } from 'react-joyride'

export const MODEL_ASSIGNMENT_TOUR_ID = 'model-assignment-tour'

// Tour 步骤定义
export const modelAssignmentTourSteps: Step[] = [
  {
    target: 'body',
    content: '本引导会帮你在同一个页面完成模型厂商、模型列表和功能分配配置。',
    placement: 'center' as Placement,
    disableBeacon: true,
    disableOverlayClose: true,
    hideCloseButton: false,
    spotlightClicks: false,
  },
  {
    target: '[data-tour="providers-tab-trigger"]',
    content: '第一步，进入“模型设置”。左侧用于管理模型厂商，右侧用于查看和配置对应模型。',
    placement: 'bottom' as Placement,
    disableBeacon: true,
    disableOverlayClose: true,
    hideCloseButton: false,
    spotlightClicks: true,
    hideFooter: true,
  },
  {
    target: '[data-tour="add-provider-button"]',
    content: '点击"添加提供商"按钮，开始配置模型厂商的连接信息。',
    placement: 'bottom' as Placement,
    disableBeacon: true,
    disableOverlayClose: true,
    hideCloseButton: false,
    spotlightClicks: true,
    hideFooter: true,
  },
  {
    target: '[data-tour="provider-dialog"]',
    content: '在这里可以选择厂商模板，填写 API Key、URL 和连接参数，保存后即可供模型引用。',
    placement: 'left' as Placement,
    disableBeacon: true,
    disableOverlayClose: true,
    hideCloseButton: false,
    spotlightClicks: false,
  },
  {
    target: '[data-tour="provider-name-input"]',
    content: '这里的名称用于在后续模型配置中识别这个厂商。',
    placement: 'bottom' as Placement,
    disableBeacon: true,
    disableOverlayClose: true,
    hideCloseButton: false,
    spotlightClicks: false,
  },
  {
    target: '[data-tour="provider-apikey-input"]',
    content: '这里填写从模型厂商获取的 API Key，用于验证并调用模型服务。',
    placement: 'bottom' as Placement,
    disableBeacon: true,
    disableOverlayClose: true,
    hideCloseButton: false,
    spotlightClicks: false,
  },
  {
    target: '[data-tour="provider-url-input"]',
    content: '这里填写模型厂商的 API 访问地址。不同厂商或平台的地址可能不同。',
    placement: 'bottom' as Placement,
    disableBeacon: true,
    disableOverlayClose: true,
    hideCloseButton: false,
    spotlightClicks: false,
  },
  {
    target: '[data-tour="provider-template-select"]',
    content: '如果不确定如何填写，可以从预设模板中选择常用厂商，相关信息会自动填充。',
    placement: 'bottom' as Placement,
    disableBeacon: true,
    disableOverlayClose: true,
    hideCloseButton: false,
    spotlightClicks: false,
  },
  {
    target: '[data-tour="provider-save-button"]',
    content: '填写完成后点击保存，模型厂商就配置好了。',
    placement: 'top' as Placement,
    disableBeacon: true,
    disableOverlayClose: true,
    hideCloseButton: false,
    spotlightClicks: false,
  },
  {
    target: '[data-tour="provider-cancel-button"]',
    content: '这次只是演示流程，点击取消关闭厂商配置窗口。',
    placement: 'top' as Placement,
    disableBeacon: true,
    disableOverlayClose: true,
    hideCloseButton: false,
    spotlightClicks: true,
    hideFooter: true,
  },
  {
    target: '[data-tour="models-tab-trigger"]',
    content: '厂商配置完成后，在右侧模型区域把具体要使用的模型加入列表。',
    placement: 'bottom' as Placement,
    disableBeacon: true,
    disableOverlayClose: true,
    hideCloseButton: false,
    spotlightClicks: true,
    hideFooter: true,
  },
  {
    target: '[data-tour="add-model-button"]',
    content: '点击"添加模型"按钮，开始添加一个可分配给功能的模型。',
    placement: 'bottom' as Placement,
    disableBeacon: true,
    disableOverlayClose: true,
    hideCloseButton: false,
    spotlightClicks: true,
    hideFooter: true,
  },
  {
    target: '[data-tour="model-dialog"]',
    content: '在这里选择刚才配置好的厂商，并填写模型名称、标识符、价格和能力参数。',
    placement: 'left' as Placement,
    disableBeacon: true,
    disableOverlayClose: true,
    hideCloseButton: false,
    spotlightClicks: false,
  },
  {
    target: '[data-tour="model-name-input"]',
    content: '模型名称用于在任务分配时识别这个模型。',
    placement: 'bottom' as Placement,
    disableBeacon: true,
    disableOverlayClose: true,
    hideCloseButton: false,
    spotlightClicks: false,
  },
  {
    target: '[data-tour="model-provider-select"]',
    content: '这里选择模型所属的厂商，系统会根据厂商配置获取或调用对应模型。',
    placement: 'bottom' as Placement,
    disableBeacon: true,
    disableOverlayClose: true,
    hideCloseButton: false,
    spotlightClicks: false,
  },
  {
    target: '[data-tour="model-identifier-input"]',
    content: '这里填写模型标识符。不同厂商的模型标识符格式可能不同，请参考对应厂商文档。',
    placement: 'bottom' as Placement,
    disableBeacon: true,
    disableOverlayClose: true,
    hideCloseButton: false,
    spotlightClicks: false,
  },
  {
    target: '[data-tour="model-save-button"]',
    content: '填写完成后点击保存，模型就会加入可用模型列表。',
    placement: 'top' as Placement,
    disableBeacon: true,
    disableOverlayClose: true,
    hideCloseButton: false,
    spotlightClicks: false,
  },
  {
    target: '[data-tour="model-cancel-button"]',
    content: '这次只是演示流程，点击取消关闭模型配置窗口。',
    placement: 'top' as Placement,
    disableBeacon: true,
    disableOverlayClose: true,
    hideCloseButton: false,
    spotlightClicks: true,
    hideFooter: true,
  },
  {
    target: '[data-tour="tasks-tab-trigger"]',
    content: '最后切换到"为模型分配功能"，为麦麦的各个组件选择合适的模型。',
    placement: 'bottom' as Placement,
    disableBeacon: true,
    disableOverlayClose: true,
    hideCloseButton: false,
    spotlightClicks: true,
    hideFooter: true,
  },
  {
    target: '[data-tour="task-model-select"]',
    content: '在这里可以为每个组件选择一个或多个模型，选择完成后配置会自动保存。',
    placement: 'bottom' as Placement,
    disableBeacon: true,
    disableOverlayClose: true,
    hideCloseButton: false,
    spotlightClicks: false,
  },
]

// 需要用户点击才能继续的步骤索引（0-based）
export const CLICK_TO_CONTINUE_STEPS = new Set([1, 2, 9, 10, 11, 17, 18])

// 合并后所有步骤都在模型管理与分配页面内完成
export const STEP_ROUTE_MAP: Record<number, string> = Object.fromEntries(
  modelAssignmentTourSteps.map((_, index) => [index, '/config/model'])
)
